import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

export default function TermsAndConditions() {
    return (
        <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
            <div className="max-w-4xl mx-auto bg-white rounded-2xl shadow-sm border border-gray-100 p-8 md:p-12">
                <Link to="/" className="inline-flex items-center text-gray-500 hover:text-gray-900 mb-8 transition-colors">
                    <ArrowLeft className="w-4 h-4 mr-2" />
                    Back to Home
                </Link>

                <h1 className="text-4xl font-bold text-gray-900 mb-8">Terms and Conditions</h1>

                <div className="space-y-6 text-gray-600 leading-relaxed text-lg">
                    <p><strong>Effective Date:</strong> March 2026</p>
                    <p>This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>

                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">1. Acceptance of Terms</h2>
                    <p>By accessing and using MathLogs, you accept and agree to be bound by these Terms and Conditions. If you do not agree to these terms, you may not access or use the application.</p>

                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">2. Description of Service</h2>
                    <p>MathLogs is a coaching management platform designed to help teachers manage student records, track fees, record test marks, and automate parent notifications through WhatsApp and email.</p>

                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">3. User Responsibilities & Data Protection Compliance</h2>
                    <ul className="list-disc pl-6 space-y-2">
                        <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
                        <li>You act as a Data Fiduciary under the Digital Personal Data Protection (DPDP) Act, 2023. You must ensure you have explicit, verifiable consent from students or their legal guardians before adding their data to our platform.</li>
                        <li>You agree not to use the service for any illegal or unauthorized purpose, or to upload content prohibited under Section 79 of the IT Act, 2000.</li>
                        <li>You are solely responsible for compliance with any local regulations regarding student data privacy in your region.</li>
                    </ul>

                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">4. WhatsApp and Email Communication</h2>
                    <p>The platform enables the sending of automated messages to parents regarding fees, marks, and announcements. You agree to use this feature responsibly and not for spam or unsolicited marketing communications. We reserve the right to suspend email or messaging access if abuse is detected, as per telecom regulations in India.</p>

                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">5. Intellectual Property</h2>
                    <p>All content, features, and functionality of MathLogs are the exclusive property of its creators and are protected by Indian and international copyright, trademark, and other intellectual property laws.</p>

                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">6. Limitation of Liability</h2>
                    <p>In no event shall MathLogs, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the service.</p>

                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">7. Governing Law and Jurisdiction</h2>
                    <p>These Terms shall be governed and construed in accordance with the laws of India. Any disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the competent courts in India.</p>

                    <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">8. Changes to Terms</h2>
                    <p>We reserve the right to modify or replace these Terms at any time. We will provide notice of any material changes via the application.</p>
                </div>
            </div>
        </div>
    );
}
