import { useCallback, useDeferredValue, useEffect, useState } from 'react';
import { ExternalLink, Search, SlidersHorizontal } from 'lucide-react';
import { marketplaceApi } from './api';
import { ListingEditorDrawer } from './ListingEditorDrawer';
import type { MarketplaceListing } from './types';
import { EmptyState, PanelError, StatusBadge, TableSkeleton } from './ui';

const filters = ['all', 'public', 'hidden', 'verified', 'unverified', 'claimed', 'unclaimed', 'google-connected', 'google-stale', 'incomplete'];

export function ListingsPanel({ initialFilter, initialQuery, refreshKey, onChanged, onDirtyChange }: { initialFilter?: string; initialQuery?: string; refreshKey: number; onChanged: () => void; onDirtyChange: (isDirty: boolean) => void }) {
  const [query, setQuery] = useState(initialQuery || '');
  const deferredQuery = useDeferredValue(query);
  const [filter, setFilter] = useState(initialFilter || 'all');
  const [listings, setListings] = useState<MarketplaceListing[]>([]);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setListings(await marketplaceApi.getListings({ query: deferredQuery, filter: filter === 'all' ? undefined : filter })); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load listings'); } finally { setLoading(false); } }, [deferredQuery, filter]);
  useEffect(() => { void load(); }, [load, refreshKey]);
  useEffect(() => { if (initialFilter) setFilter(initialFilter); }, [initialFilter]);
  useEffect(() => { if (initialQuery !== undefined) setQuery(initialQuery); }, [initialQuery]);
  const changed = () => { onChanged(); void load(); };
  return <div className="space-y-4">
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="text-lg font-black tracking-tight">Listings</h2><p className="text-xs text-neutral-500">Quality, visibility, ownership and Google connection control.</p></div><div className="flex items-center gap-2"><label className="flex flex-1 items-center gap-2 rounded-xl border border-neutral-200 bg-white px-3 py-2.5 sm:w-72"><Search className="h-4 w-4 text-neutral-400" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Coaching, teacher, phone, city…" className="min-w-0 flex-1 text-xs outline-none" /></label></div></div>
    <div className="flex gap-2 overflow-x-auto pb-1"><SlidersHorizontal className="mt-2 h-4 w-4 shrink-0 text-neutral-400" />{filters.map(value => <button key={value} onClick={() => setFilter(value)} className={`whitespace-nowrap rounded-full px-3 py-2 text-xs font-bold ${filter === value ? 'bg-neutral-950 text-white' : 'border border-neutral-200 bg-white text-neutral-600 hover:bg-neutral-50'}`}>{value === 'all' ? 'All listings' : value === 'google-connected' ? 'Google connected' : value === 'google-stale' ? 'Google stale' : value}</button>)}</div>
    <section className="overflow-hidden rounded-2xl border border-neutral-200 bg-white shadow-sm">{loading ? <TableSkeleton /> : error ? <PanelError message={error} retry={() => void load()} /> : listings.length === 0 ? <EmptyState title="No listings match this view" detail="Try another filter or search by a different coaching detail." /> : <><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[940px] text-left"><thead className="border-b border-neutral-200 bg-neutral-50 text-[10px] uppercase tracking-wide text-neutral-500"><tr><th className="px-5 py-3">Listing</th><th className="px-4 py-3">Trust & owner</th><th className="px-4 py-3">Profile</th><th className="px-4 py-3">Google</th><th className="px-4 py-3">Activity</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody>{listings.map(listing => <ListingTableRow key={listing.id} listing={listing} onOpen={() => setSelectedId(listing.id)} />)}</tbody></table></div><div className="divide-y divide-neutral-100 md:hidden">{listings.map(listing => <button key={listing.id} onClick={() => setSelectedId(listing.id)} className="w-full p-4 text-left"><div className="flex items-start gap-3"><ListingAvatar listing={listing} /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-black">{listing.name}</span><span className="block truncate text-xs text-neutral-500">{[listing.teacherName, listing.city, listing.area].filter(Boolean).join(' · ') || 'Location missing'}</span><span className="mt-2 flex flex-wrap gap-1"><StatusBadge value={listing.isPubliclyListed ? 'PUBLIC' : 'HIDDEN'} /><StatusBadge value={listing.isVerified ? 'VERIFIED' : 'UNVERIFIED'} /><StatusBadge value={listing.ownershipStatus || 'UNCLAIMED'} /></span></span></div></button>)}</div></>}</section>
    {selectedId && <ListingEditorDrawer listingId={selectedId} onClose={() => setSelectedId(null)} onChanged={changed} onDirtyChange={onDirtyChange} />}
  </div>;
}

function ListingAvatar({ listing }: { listing: MarketplaceListing }) { return listing.logoUrl ? <img src={listing.logoUrl} alt="" className="h-9 w-9 rounded-xl border border-neutral-200 object-cover" /> : <span className="grid h-9 w-9 place-items-center rounded-xl bg-neutral-100 text-xs font-black text-neutral-500">{listing.name.slice(0, 1)}</span>; }
function ListingTableRow({ listing, onOpen }: { listing: MarketplaceListing; onOpen: () => void }) { return <tr className="border-b border-neutral-100 last:border-0 hover:bg-neutral-50"><td className="px-5 py-3"><div className="flex items-center gap-3"><ListingAvatar listing={listing} /><div className="min-w-0"><p className="max-w-52 truncate text-xs font-black">{listing.name}</p><p className="max-w-52 truncate text-[11px] text-neutral-500">{[listing.teacherName, listing.city, listing.area].filter(Boolean).join(' · ') || 'Location missing'}</p></div></div></td><td className="px-4 py-3"><div className="flex flex-wrap gap-1"><StatusBadge value={listing.isPubliclyListed ? 'PUBLIC' : 'HIDDEN'} /><StatusBadge value={listing.isVerified ? 'VERIFIED' : 'UNVERIFIED'} /><StatusBadge value={listing.ownershipStatus || 'UNCLAIMED'} /></div></td><td className="px-4 py-3"><p className="text-xs font-bold">{listing.profileCompleteness ?? 0}%</p><p className="text-[11px] text-neutral-500">{listing.plan || 'Standard'} plan</p></td><td className="px-4 py-3">{listing.googlePlaceId ? <span className="text-xs font-bold text-emerald-700">Connected</span> : <span className="text-xs text-neutral-400">Not connected</span>}<p className="text-[11px] text-neutral-500">{listing.googleRating ? `${listing.googleRating} ★ · ${listing.googleReviewCount || 0}` : ''}</p></td><td className="px-4 py-3 text-xs text-neutral-600">{listing._count?.reviews || 0} reviews<br />{listing._count?.leadInquiries || 0} inquiries</td><td className="px-5 py-3 text-right"><a href={listing.slug ? `/coaching/${listing.slug}` : '#'} target="_blank" rel="noreferrer" onClick={event => { if (!listing.slug) event.preventDefault(); }} className="mr-2 inline-flex rounded-lg p-2 text-neutral-500 hover:bg-neutral-100" aria-label={`Preview ${listing.name}`}><ExternalLink className="h-4 w-4" /></a><button onClick={onOpen} className="rounded-lg border border-neutral-200 px-3 py-1.5 text-xs font-bold hover:bg-white">Open</button></td></tr>; }
