import { useCallback, useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { RefreshCw, Search } from 'lucide-react';
import { BillingOperationDialog } from '../../features/superadmin-revenue/BillingOperationDialog';
import { RevenueOverview } from '../../features/superadmin-revenue/RevenueOverview';
import { SubscriptionTable } from '../../features/superadmin-revenue/SubscriptionTable';
import { superAdminRevenueApi } from '../../features/superadmin-revenue/api';
import type { RevenueOverviewData, SubscriptionItem, SubscriptionResponse } from '../../features/superadmin-revenue/types';

export default function SuperAdminRevenue() {
  const [params, setParams] = useSearchParams();
  const [overview, setOverview] = useState<RevenueOverviewData | null>(null);
  const [subscriptions, setSubscriptions] = useState<SubscriptionResponse | null>(null);
  const [selected, setSelected] = useState<SubscriptionItem | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [query, setQuery] = useState(params.get('q') || '');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [nextOverview, nextSubscriptions] = await Promise.all([superAdminRevenueApi.overview(), superAdminRevenueApi.subscriptions({ q: params.get('q') || undefined, plan: params.get('plan') || undefined, page: Number(params.get('page') || 1), pageSize: 25 })]); setOverview(nextOverview); setSubscriptions(nextSubscriptions); const instituteId = params.get('instituteId'); if (instituteId) setSelected(nextSubscriptions.items.find(item => item.instituteId === instituteId) || { instituteId, name: 'Selected institute', teacherName: null, status: '', plan: '', planStartDate: null, planExpiryDate: null, updatedAt: '' }); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load revenue operations'); } finally { setLoading(false); } }, [params]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { const timer = setTimeout(() => { const next = new URLSearchParams(params); if (query.trim()) next.set('q', query.trim()); else next.delete('q'); if (next.toString() !== params.toString()) setParams(next, { replace: true }); }, 250); return () => clearTimeout(timer); }, [query]); // eslint-disable-line react-hooks/exhaustive-deps
  return <div className="mx-auto max-w-[1500px] space-y-6"><section className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[0.2em] text-amber-700">Revenue operations</p><h2 className="mt-2 text-3xl font-black">Plans, trials, credits, and payment records.</h2><p className="mt-2 text-sm text-stone-600">MathLogs subscription state only—coaching fee collections remain separate.</p></div><button onClick={() => void load()} className="inline-flex items-center gap-2 rounded-2xl border border-stone-200 bg-white px-4 py-3 text-sm font-black"><RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />Refresh</button></section>{error ? <p className="rounded-2xl bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</p> : null}{overview ? <RevenueOverview data={overview} /> : null}<section className="rounded-[28px] border border-stone-200 bg-[#fffdf9] shadow-sm"><div className="grid gap-3 border-b border-stone-200 p-5 sm:grid-cols-[1fr_180px]"><label className="flex items-center gap-2 rounded-2xl border border-stone-200 bg-white px-3 py-2.5"><Search className="h-4 w-4 text-stone-400" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search subscriptions" className="min-w-0 flex-1 bg-transparent text-sm outline-none" /></label><select value={params.get('plan') || ''} onChange={event => { const next = new URLSearchParams(params); if (event.target.value) next.set('plan', event.target.value); else next.delete('plan'); setParams(next); }} className="rounded-2xl border border-stone-200 bg-white px-3 py-2.5 text-sm font-bold"><option value="">All plans</option><option>FREE</option><option>BASIC</option><option>PRO</option><option>ENTERPRISE</option><option>NO_PLAN</option></select></div>{subscriptions ? <SubscriptionTable items={subscriptions.items} onOperate={setSelected} /> : <div className="p-10 text-center text-sm text-stone-500">Loading subscriptions…</div>}</section>{selected ? <BillingOperationDialog open instituteId={selected.instituteId} instituteName={selected.name} onClose={() => { setSelected(null); const next = new URLSearchParams(params); next.delete('instituteId'); setParams(next, { replace: true }); }} onSuccess={() => void load()} /> : null}</div>;
}
