import { useEffect, useMemo, useState } from 'react';
import { CalendarClock, CheckCircle2, Loader2, ShieldCheck, X } from 'lucide-react';
import { useSuperAdminReauth } from '../superadmin-shell/ReauthDialog';
import { superAdminRevenueApi } from './api';
import type { BillingOperationDraft, BillingPreview } from './types';

const protectedTypes = new Set(['PLAN_REVOKE', 'QUIZ_CREDIT_ADJUSTMENT', 'MANUAL_PAYMENT_REFERENCE']);

function initialDraft(): BillingOperationDraft { return { type: 'PLAN_CHANGE', reason: '', payload: { plan: 'BASIC', expiryDate: new Date(Date.now() + 365 * 86_400_000).toISOString().slice(0, 10) } }; }

export function BillingOperationDialog({ instituteId, instituteName, open, onClose, onSuccess }: { instituteId: string; instituteName: string; open: boolean; onClose: () => void; onSuccess: () => void }) {
  const [draft, setDraft] = useState<BillingOperationDraft>(initialDraft);
  const [preview, setPreview] = useState<BillingPreview | null>(null);
  const [idempotencyKey, setIdempotencyKey] = useState(() => crypto.randomUUID());
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const reauth = useSuperAdminReauth();
  useEffect(() => { if (open) { setDraft(initialDraft()); setPreview(null); setError(''); setIdempotencyKey(crypto.randomUUID()); } }, [open, instituteId]);
  const isProtected = protectedTypes.has(draft.type);
  const payloadFields = useMemo(() => {
    if (draft.type === 'PLAN_CHANGE') return ['plan', 'expiryDate'];
    if (draft.type === 'TRIAL_EXTENSION') return ['days'];
    if (draft.type === 'STUDENT_LIMIT_ADJUSTMENT') return ['maxStudents'];
    if (draft.type === 'QUIZ_CREDIT_ADJUSTMENT') return ['delta'];
    if (draft.type === 'MANUAL_PAYMENT_REFERENCE') return ['amountPaise', 'reference', 'paidAt'];
    return [];
  }, [draft.type]);
  if (!open) return null;
  const setType = (type: BillingOperationDraft['type']) => { const payload = type === 'PLAN_CHANGE' ? { plan: 'BASIC', expiryDate: new Date(Date.now() + 365 * 86_400_000).toISOString().slice(0, 10) } : type === 'TRIAL_EXTENSION' ? { days: 14 } : type === 'STUDENT_LIMIT_ADJUSTMENT' ? { maxStudents: 100 } : type === 'QUIZ_CREDIT_ADJUSTMENT' ? { delta: 10 } : type === 'MANUAL_PAYMENT_REFERENCE' ? { amountPaise: 99900, reference: '', paidAt: new Date().toISOString().slice(0, 10) } : {}; setDraft(current => ({ ...current, type, payload })); setPreview(null); };
  const doPreview = async () => { setBusy(true); setError(''); try { setPreview(await superAdminRevenueApi.preview(instituteId, draft)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Preview failed'); } finally { setBusy(false); } };
  const apply = async () => { if (!preview) return; setBusy(true); setError(''); try { const challengeId = preview.protected && preview.actionClass ? await reauth.request(preview.actionClass) : undefined; await superAdminRevenueApi.apply(instituteId, draft, idempotencyKey, challengeId); onSuccess(); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Operation failed'); } finally { setBusy(false); } };
  const input = 'w-full rounded-xl border border-stone-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-amber-500';
  return <div className="fixed inset-0 z-[80] grid place-items-center bg-stone-950/45 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="Billing operation"><div className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-[28px] border border-stone-200 bg-[#fffdf9] shadow-2xl"><div className="flex items-start gap-4 border-b border-stone-200 p-6"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-amber-100"><CalendarClock className="h-5 w-5 text-amber-900" /></div><div className="flex-1"><p className="text-xs font-black uppercase tracking-wider text-amber-700">Guarded billing operation</p><h2 className="mt-1 text-2xl font-black">{instituteName}</h2></div><button onClick={onClose} className="rounded-xl p-2 hover:bg-stone-100" aria-label="Close billing dialog"><X className="h-4 w-4" /></button></div><div className="space-y-5 p-6">
    <div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-bold">Operation</span><select value={draft.type} onChange={event => setType(event.target.value as BillingOperationDraft['type'])} className={input}><option value="PLAN_CHANGE">Plan change</option><option value="TRIAL_EXTENSION">Trial extension</option><option value="STUDENT_LIMIT_ADJUSTMENT">Student limit</option><option value="QUIZ_CREDIT_ADJUSTMENT">Quiz credits</option><option value="PLAN_REVOKE">Revoke plan</option><option value="MANUAL_PAYMENT_REFERENCE">Manual payment reference</option></select></label><label><span className="mb-2 block text-sm font-bold">Effective at (optional)</span><input type="datetime-local" className={input} value={draft.effectiveAt || ''} onChange={event => { setDraft(current => ({ ...current, effectiveAt: event.target.value || undefined })); setPreview(null); }} /></label></div>
    {payloadFields.length ? <div className="grid gap-4 sm:grid-cols-2">{payloadFields.map(field => <label key={field} className={field === 'reference' ? 'sm:col-span-2' : ''}><span className="mb-2 block text-sm font-bold">{field.replaceAll(/([A-Z])/g, ' $1')}</span>{field === 'plan' ? <select className={input} value={String(draft.payload[field] || '')} onChange={event => { setDraft(current => ({ ...current, payload: { ...current.payload, [field]: event.target.value } })); setPreview(null); }}><option>FREE</option><option>BASIC</option><option>PRO</option><option>ENTERPRISE</option></select> : <input className={input} type={field.includes('Date') || field === 'paidAt' ? 'date' : ['days', 'maxStudents', 'delta', 'amountPaise'].includes(field) ? 'number' : 'text'} value={String(draft.payload[field] ?? '')} onChange={event => { const value = ['days', 'maxStudents', 'delta', 'amountPaise'].includes(field) ? Number(event.target.value) : event.target.value; setDraft(current => ({ ...current, payload: { ...current.payload, [field]: value } })); setPreview(null); }} />}</label>)}</div> : null}
    <label><span className="mb-2 block text-sm font-bold">Reason</span><textarea className={`${input} min-h-24 resize-y`} value={draft.reason} onChange={event => { setDraft(current => ({ ...current, reason: event.target.value })); setPreview(null); }} placeholder="Explain the verified business reason for the audit trail" /></label>
    {isProtected ? <p className="flex items-center gap-2 rounded-xl bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-900"><ShieldCheck className="h-4 w-4" />A fresh OTP is requested only when you apply this operation.</p> : null}
    {preview ? <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex items-center gap-2 font-black text-emerald-800"><CheckCircle2 className="h-5 w-5" />Preview ready {preview.scheduled ? '· scheduled' : '· immediate'}</div><div className="mt-4 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-white/70 p-3"><p className="text-[10px] font-black uppercase text-stone-400">Before</p><pre className="mt-2 whitespace-pre-wrap text-xs">{JSON.stringify(preview.before, null, 2)}</pre></div><div className="rounded-xl bg-white/70 p-3"><p className="text-[10px] font-black uppercase text-stone-400">After</p><pre className="mt-2 whitespace-pre-wrap text-xs">{JSON.stringify(preview.after, null, 2)}</pre></div></div></div> : null}
    {error ? <p className="rounded-xl bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">{error}</p> : null}
  </div><div className="flex items-center justify-end gap-3 border-t border-stone-200 p-5"><button onClick={onClose} className="rounded-xl px-4 py-2.5 text-sm font-bold">Cancel</button>{preview ? <button onClick={() => void apply()} disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-stone-950 px-4 py-2.5 text-sm font-black text-white disabled:opacity-50">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : null}Apply operation</button> : <button onClick={() => void doPreview()} disabled={busy || draft.reason.trim().length < 10} className="inline-flex items-center gap-2 rounded-xl bg-stone-950 px-4 py-2.5 text-sm font-black text-white disabled:opacity-50">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : null}Preview changes</button>}</div></div></div>;
}
