import type { Request, Response } from 'express';
import { getSystemOverview, listSystemAudit, listSystemJobs, listSystemSecurity, retrySystemJob, revokeSystemSession, SystemServiceError } from '../services/superAdminSystemService';

function failure(res: Response, error: unknown) { const code = error instanceof Error ? error.message : 'SYSTEM_OPERATION_FAILED'; const known = error instanceof SystemServiceError || ['IDEMPOTENCY_KEY_REUSED', 'IDEMPOTENCY_IN_PROGRESS'].includes(code); const status = code.endsWith('NOT_FOUND') ? 404 : code.includes('ALREADY') || code.startsWith('IDEMPOTENCY_') || code === 'JOB_NOT_RETRYABLE' ? 409 : known ? 400 : 500; return res.status(status).json({ success: false, error: known ? code : 'SYSTEM_OPERATION_FAILED' }); }
export async function overview(_req: Request, res: Response) { try { return res.json({ success: true, data: await getSystemOverview() }); } catch (error) { return failure(res, error); } }
export async function jobs(req: Request, res: Response) { try { return res.json({ success: true, data: await listSystemJobs({ kind: String(req.query.kind || '') || undefined, status: String(req.query.status || '') || undefined, q: String(req.query.q || '').trim() || undefined }) }); } catch (error) { return failure(res, error); } }
export async function retryJob(req: Request, res: Response) { try { return res.json({ success: true, data: await retrySystemJob({ kind: String(req.params.kind).toUpperCase(), id: String(req.params.id), actorAdminId: req.user.id, correlationId: req.correlationId, idempotencyKey: String(req.header('Idempotency-Key') || '').trim(), reason: String(req.body?.reason || '') }) }); } catch (error) { return failure(res, error); } }
export async function audit(req: Request, res: Response) { try { return res.json({ success: true, data: await listSystemAudit({ q: String(req.query.q || '').trim() || undefined, instituteId: String(req.query.instituteId || '') || undefined, actorAdminId: String(req.query.actorAdminId || '') || undefined }) }); } catch (error) { return failure(res, error); } }
export async function security(_req: Request, res: Response) { try { return res.json({ success: true, data: await listSystemSecurity() }); } catch (error) { return failure(res, error); } }
export async function revokeSession(req: Request, res: Response) { try { return res.json({ success: true, data: await revokeSystemSession({ sessionId: String(req.params.id), actorAdminId: req.user.id, correlationId: req.correlationId, reason: String(req.body?.reason || '') }) }); } catch (error) { return failure(res, error); } }
