import type { Request, Response } from 'express';
import { CommunicationServiceError, dispatchTargetedCommunication, getCommunicationPreference, listApprovedCommunicationTemplates, listTargetedCommunicationHistory, previewTargetedCommunication, updateCommunicationPreference } from '../services/superAdminCommunicationService';

function failure(res: Response, error: unknown) { const code = error instanceof Error ? error.message : 'COMMUNICATION_OPERATION_FAILED'; const known = error instanceof CommunicationServiceError || ['IDEMPOTENCY_KEY_REUSED', 'IDEMPOTENCY_IN_PROGRESS'].includes(code); return res.status(known ? (code.startsWith('IDEMPOTENCY_') ? 409 : 400) : 500).json({ success: false, error: known ? code : 'COMMUNICATION_OPERATION_FAILED' }); }
export function templates(_req: Request, res: Response) { return res.json({ success: true, data: listApprovedCommunicationTemplates() }); }
export async function preview(req: Request, res: Response) { try { return res.json({ success: true, data: await previewTargetedCommunication(req.body) }); } catch (error) { return failure(res, error); } }
export async function dispatch(req: Request, res: Response) { try { return res.status(201).json({ success: true, data: await dispatchTargetedCommunication({ value: req.body, actorAdminId: req.user.id, correlationId: req.correlationId, idempotencyKey: String(req.header('Idempotency-Key') || '').trim() }) }); } catch (error) { return failure(res, error); } }
export async function history(_req: Request, res: Response) { try { return res.json({ success: true, data: await listTargetedCommunicationHistory() }); } catch (error) { return failure(res, error); } }
export async function getPreference(req: Request, res: Response) { try { return res.json({ success: true, data: await getCommunicationPreference(String(req.params.id)) }); } catch (error) { return failure(res, error); } }
export async function updatePreference(req: Request, res: Response) { const reason = String(req.body?.reason || '').trim(); if (reason.length < 10) return res.status(400).json({ success: false, error: 'REASON_REQUIRED' }); try { return res.json({ success: true, data: await updateCommunicationPreference({ instituteId: String(req.params.id), whatsappOperational: typeof req.body?.whatsappOperational === 'boolean' ? req.body.whatsappOperational : undefined, emailOperational: typeof req.body?.emailOperational === 'boolean' ? req.body.emailOperational : undefined, consentSource: 'SUPERADMIN_VERIFIED', actorAdminId: req.user.id, correlationId: req.correlationId, reason }) }); } catch (error) { return failure(res, error); } }
export async function getOwnPreference(req: Request, res: Response) { if (!req.user.instituteId) return res.status(403).json({ success: false, error: 'INSTITUTE_REQUIRED' }); try { return res.json({ success: true, data: await getCommunicationPreference(req.user.instituteId) }); } catch (error) { return failure(res, error); } }
export async function updateOwnPreference(req: Request, res: Response) { if (!req.user.instituteId) return res.status(403).json({ success: false, error: 'INSTITUTE_REQUIRED' }); try { return res.json({ success: true, data: await updateCommunicationPreference({ instituteId: req.user.instituteId, whatsappOperational: typeof req.body?.whatsappOperational === 'boolean' ? req.body.whatsappOperational : undefined, emailOperational: typeof req.body?.emailOperational === 'boolean' ? req.body.emailOperational : undefined, consentSource: 'INSTITUTE_SETTINGS' }) }); } catch (error) { return failure(res, error); } }
