import type { Request, Response } from 'express';
import { addInternalCaseNote, addSupportMessage, createInternalCase, createSupportTicket, getInternalCase, getSupportTicket, listInternalCases, listSupportTickets, SupportServiceError, transitionSupportTicket } from '../services/superAdminSupportService';

function failure(res: Response, error: unknown) { if (!(error instanceof SupportServiceError)) return res.status(500).json({ success: false, error: 'SUPPORT_OPERATION_FAILED' }); if (['SUPPORT_TICKET_NOT_FOUND', 'INTERNAL_CASE_NOT_FOUND', 'INSTITUTE_NOT_FOUND'].includes(error.message)) return res.status(404).json({ success: false, error: error.message }); if (error.message === 'STALE_SUPPORT_TICKET') return res.status(409).json({ success: false, error: error.message, data: error.current }); return res.status(400).json({ success: false, error: error.message }); }
export async function createInstituteTicket(req: Request, res: Response) { if (!req.user.instituteId) return res.status(403).json({ success: false, error: 'INSTITUTE_REQUIRED' }); try { return res.status(201).json({ success: true, data: await createSupportTicket(req.user.instituteId, req.body) }); } catch (error) { return failure(res, error); } }
export async function listInstituteTickets(req: Request, res: Response) { if (!req.user.instituteId) return res.status(403).json({ success: false, error: 'INSTITUTE_REQUIRED' }); try { return res.json({ success: true, data: await listSupportTickets({ instituteId: req.user.instituteId }) }); } catch (error) { return failure(res, error); } }
export async function getInstituteTicket(req: Request, res: Response) { try { return res.json({ success: true, data: await getSupportTicket(String(req.params.id), req.user.instituteId) }); } catch (error) { return failure(res, error); } }
export async function replyInstituteTicket(req: Request, res: Response) { try { return res.status(201).json({ success: true, data: await addSupportMessage({ ticketId: String(req.params.id), instituteId: req.user.instituteId, authorAdminId: req.user.id, visibility: 'PUBLIC', body: String(req.body?.body || ''), expectedUpdatedAt: String(req.body?.expectedUpdatedAt || ''), correlationId: req.correlationId }) }); } catch (error) { return failure(res, error); } }
export async function listAllTickets(req: Request, res: Response) { try { return res.json({ success: true, data: await listSupportTickets({ instituteId: String(req.query.instituteId || '') || undefined, status: String(req.query.status || '').toUpperCase() || undefined, priority: String(req.query.priority || '').toUpperCase() || undefined, category: String(req.query.category || '').toUpperCase() || undefined, q: String(req.query.q || '').trim() || undefined }) }); } catch (error) { return failure(res, error); } }
export async function getAnyTicket(req: Request, res: Response) { try { return res.json({ success: true, data: await getSupportTicket(String(req.params.id)) }); } catch (error) { return failure(res, error); } }
export async function addTicketMessage(req: Request, res: Response) { const visibility = String(req.body?.visibility || 'PUBLIC').toUpperCase(); if (!['PUBLIC', 'INTERNAL'].includes(visibility)) return res.status(400).json({ success: false, error: 'INVALID_VISIBILITY' }); try { return res.status(201).json({ success: true, data: await addSupportMessage({ ticketId: String(req.params.id), authorAdminId: req.user.id, visibility: visibility as 'PUBLIC' | 'INTERNAL', body: String(req.body?.body || ''), expectedUpdatedAt: String(req.body?.expectedUpdatedAt || ''), correlationId: req.correlationId }) }); } catch (error) { return failure(res, error); } }
export async function updateTicketStatus(req: Request, res: Response) { try { return res.json({ success: true, data: await transitionSupportTicket({ ticketId: String(req.params.id), actorAdminId: req.user.id, status: String(req.body?.status || ''), resolutionSummary: req.body?.resolutionSummary, expectedUpdatedAt: String(req.body?.expectedUpdatedAt || ''), correlationId: req.correlationId }) }); } catch (error) { return failure(res, error); } }
export async function createCase(req: Request, res: Response) { try { return res.status(201).json({ success: true, data: await createInternalCase({ actorAdminId: req.user.id, correlationId: req.correlationId, value: req.body }) }); } catch (error) { return failure(res, error); } }
export async function listCases(req: Request, res: Response) { try { return res.json({ success: true, data: await listInternalCases({ instituteId: String(req.query.instituteId || '') || undefined, status: String(req.query.status || '').toUpperCase() || undefined }) }); } catch (error) { return failure(res, error); } }
export async function getCase(req: Request, res: Response) { try { return res.json({ success: true, data: await getInternalCase(String(req.params.id)) }); } catch (error) { return failure(res, error); } }
export async function addCaseNote(req: Request, res: Response) { try { return res.status(201).json({ success: true, data: await addInternalCaseNote({ id: String(req.params.id), actorAdminId: req.user.id, body: String(req.body?.body || ''), correlationId: req.correlationId }) }); } catch (error) { return failure(res, error); } }
