import { parentPort, workerData } from 'worker_threads';

type BatchPdfData = {
    batchName: string;
    subject: string | null;
    columns: Array<{ id: string; label: string }>;
    rows: string[][];
};

function addHeader(doc: PDFKit.PDFDocument, x: number) {
    doc.font('Helvetica-Bold').fontSize(14).fillColor('#111827').text('MathLogs', x, 24);
}

async function generate(data: BatchPdfData): Promise<Buffer> {
    const PDFDocument = require('pdfkit');
    const columnWidth = 130;
    const pageWidth = Math.max(842, 60 + data.columns.length * columnWidth);
    const pageHeight = 595;
    const doc = new PDFDocument({ size: [pageWidth, pageHeight], margin: 30 });
    const chunks: Buffer[] = [];
    doc.on('data', (chunk: Buffer) => chunks.push(chunk));

    return new Promise((resolve, reject) => {
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        const startX = 30;
        const rowHeight = 28;
        const tableWidth = data.columns.length * columnWidth;

        const drawTitle = () => {
            addHeader(doc, startX);
            doc.font('Helvetica-Bold').fontSize(18).fillColor('#111827')
                .text(`${data.batchName} - Student Details`, startX, 52, { width: tableWidth, align: 'center' });
            doc.font('Helvetica').fontSize(10).fillColor('#6b7280')
                .text(`Subject: ${data.subject || 'N/A'} | Generated: ${new Date().toLocaleDateString('en-IN')}`, startX, 77, { width: tableWidth, align: 'center' });
        };

        const drawRow = (values: string[], y: number, header = false, alternate = false) => {
            if (header || alternate) {
                doc.fillColor(header ? '#e5e7eb' : '#f9fafb').rect(startX, y, tableWidth, rowHeight).fill();
            }
            doc.strokeColor('#d1d5db').lineWidth(0.7).rect(startX, y, tableWidth, rowHeight).stroke();
            values.forEach((value, index) => {
                const x = startX + index * columnWidth;
                if (index > 0) doc.moveTo(x, y).lineTo(x, y + rowHeight).stroke();
                doc.font(header ? 'Helvetica-Bold' : 'Helvetica').fontSize(header ? 9 : 8.5).fillColor('#111827')
                    .text(String(value || '-'), x + 4, y + 9, { width: columnWidth - 8, height: rowHeight - 8, ellipsis: true, lineBreak: false });
            });
        };

        const drawPageStart = () => {
            drawTitle();
            const headerY = 104;
            drawRow(data.columns.map(column => column.label), headerY, true);
            return headerY + rowHeight;
        };

        let y = drawPageStart();
        data.rows.forEach((row, index) => {
            if (y + rowHeight > pageHeight - 42) {
                doc.addPage({ size: [pageWidth, pageHeight], margin: 30 });
                y = drawPageStart();
            }
            drawRow(row, y, false, index % 2 === 1);
            y += rowHeight;
        });
        doc.font('Helvetica').fontSize(8.5).fillColor('#6b7280')
            .text(`Total Students: ${data.rows.length} | Generated by MathLogs`, startX, pageHeight - 28, { width: tableWidth, align: 'center' });
        doc.end();
    });
}

generate(workerData as BatchPdfData)
    .then(buffer => parentPort!.postMessage(buffer))
    .catch(error => { throw error; });
