console.log("Loading dotenv");
require("dotenv/config");
console.log("Loading path");
require("path");
console.log("Loading express");
require("express");
console.log("Loading cors");
require("cors");
console.log("Loading compression");
require("compression");
console.log("Loading api");
require("./src/routes/api");
console.log("Loading prisma");
require("./src/prisma");
console.log("Loading security");
require("./src/middleware/security");
console.log("Loading auth");
require("./src/middleware/auth");
console.log("Loading sentry");
require("./src/monitoring/sentry");
console.log("Loading Sentry node");
require("@sentry/node");
console.log("Loading health");
require("./src/monitoring/health");
console.log("Loading emailWorker");
require("./src/utils/emailWorker");
console.log("All done!");
