import { useCallback, useEffect, useMemo, useState } from 'react';
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, Building2, CalendarDays, RefreshCw, UsersRound } from 'lucide-react';
import { superAdminInstituteApi } from './api';
import { StructuredConfigForm } from './StructuredConfigForm';
import type { InstituteWorkspaceData, InstituteWorkspaceTab } from './types';

export const installedInstituteTabs: Record<InstituteWorkspaceTab, string> = { overview: 'Overview', account: 'Account', usage: 'Usage', billing: 'Billing', marketplace: 'Marketplace', leads: 'Leads', support: 'Support', activity: 'Activity' };

export function InstituteWorkspace() {
  const { id = '' } = useParams();
  const location = useLocation();
  const navigate = useNavigate();
  const tab = (location.pathname.split('/').pop() || 'overview') as InstituteWorkspaceTab;
  const activeTab = installedInstituteTabs[tab] ? tab : 'overview';
  const [data, setData] = useState<InstituteWorkspaceData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setData(await superAdminInstituteApi.get(id)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load institute'); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  const content = useMemo(() => {
    if (!data) return null;
    if (activeTab === 'overview') return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[{ label: 'Students', value: data.usage.students }, { label: 'Batches', value: data.usage.batches }, { label: 'Plan', value: data.billing.plan }, { label: 'Lead states', value: Object.values(data.leads).reduce((sum, value) => sum + value, 0) }].map(item => <div key={item.label} className="rounded-[24px] border border-stone-200 bg-white p-5"><p className="text-xs font-black uppercase tracking-wider text-stone-400">{item.label}</p><p className="mt-3 text-3xl font-black">{item.value}</p></div>)}</div>;
    if (activeTab === 'account') return <div className="space-y-3">{data.account.admins.map(admin => <div key={admin.id} className="flex items-center justify-between rounded-2xl border border-stone-200 bg-white p-4"><div><p className="font-black">{admin.username}</p><p className="text-xs text-stone-500">{admin.role}</p></div><span className="rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-black text-emerald-800">Active</span></div>)}{!data.account.admins.length ? <p className="rounded-2xl bg-amber-50 p-5 text-sm font-semibold text-amber-900">Setup invite is pending. The owner will create their phone-based login from the link sent during onboarding.</p> : null}</div>;
    if (activeTab === 'usage') return <StructuredConfigForm instituteId={id} data={data.usage} expectedUpdatedAt={data.overview.updatedAt} onSaved={() => void load()} />;
    if (activeTab === 'billing') return <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-white p-5"><p className="text-xs font-black text-stone-400">PLAN</p><p className="mt-2 text-2xl font-black">{data.billing.plan}</p></div><div className="rounded-2xl bg-white p-5"><p className="text-xs font-black text-stone-400">STARTED</p><p className="mt-2 font-black">{data.billing.planStartDate ? new Date(data.billing.planStartDate).toLocaleDateString() : '—'}</p></div><div className="rounded-2xl bg-white p-5"><p className="text-xs font-black text-stone-400">EXPIRES</p><p className="mt-2 font-black">{data.billing.planExpiryDate ? new Date(data.billing.planExpiryDate).toLocaleDateString() : '—'}</p></div></div><Link to={`/super-admin/revenue?instituteId=${id}`} className="inline-flex rounded-xl bg-stone-950 px-4 py-2.5 text-sm font-black text-white">Open billing operations</Link></div>;
    if (activeTab === 'marketplace') return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(data.marketplace).map(([key, value]) => <div key={key} className="rounded-2xl bg-white p-5"><p className="text-xs font-black uppercase text-stone-400">{key.replaceAll(/([A-Z])/g, ' $1')}</p><p className="mt-2 text-xl font-black">{String(value)}</p></div>)}</div>;
    if (activeTab === 'leads') return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(data.leads).map(([key, value]) => <div key={key} className="rounded-2xl bg-white p-5"><p className="text-xs font-black uppercase text-stone-400">{key}</p><p className="mt-2 text-3xl font-black">{value}</p></div>)}</div>;
    if (activeTab === 'support') return <div className="space-y-3">{data.support.sessions.map(session => <div key={session.id} className="rounded-2xl border border-stone-200 bg-white p-4"><p className="font-black">{session.reason}</p><p className="mt-1 text-xs text-stone-500">{session.endedAt ? 'Ended' : `Expires ${new Date(session.expiresAt).toLocaleString()}`}</p></div>)}{!data.support.sessions.length ? <p className="rounded-2xl bg-white p-6 text-sm text-stone-500">No support sessions for this institute.</p> : null}</div>;
    return <div className="space-y-3">{data.activity.map(item => <div key={`${item.source}-${item.id}`} className="flex gap-3 rounded-2xl bg-white p-4"><span className="mt-2 h-2 w-2 rounded-full bg-amber-500" /><div><p className="font-black">{item.action.replaceAll('_', ' ')}</p><p className="text-xs text-stone-500">{item.actorAdmin?.username || item.source} · {new Date(item.createdAt).toLocaleString()}</p></div></div>)}</div>;
  }, [activeTab, data, id, load]);
  if (loading && !data) return <div className="grid min-h-[50vh] place-items-center"><RefreshCw className="h-6 w-6 animate-spin" /></div>;
  if (error && !data) return <p className="rounded-2xl bg-rose-50 p-5 text-rose-700">{error}</p>;
  if (!data) return null;
  return <div className="mx-auto max-w-[1500px] space-y-5"><button onClick={() => navigate('/super-admin/institutes')} className="inline-flex items-center gap-2 text-sm font-bold text-stone-600"><ArrowLeft className="h-4 w-4" />Institutes</button><section className="rounded-[28px] border border-stone-200 bg-[#fffdf9] p-5 shadow-sm sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div className="flex gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-stone-950 text-white"><Building2 className="h-6 w-6" /></div><div><p className="text-xs font-black uppercase tracking-wider text-amber-700">{data.overview.status} · {data.overview.accessKind.replace('_', ' ')}</p><h2 className="mt-1 text-3xl font-black">{data.overview.name}</h2><p className="mt-1 text-sm text-stone-500">{data.overview.teacherName || 'Owner not set'} · {data.overview.phoneNumber || 'No phone'}</p></div></div><div className="flex gap-2"><span className="inline-flex items-center gap-2 rounded-xl bg-stone-100 px-3 py-2 text-xs font-bold"><UsersRound className="h-4 w-4" />{data.usage.students}/{data.usage.maxStudents}</span><span className="inline-flex items-center gap-2 rounded-xl bg-stone-100 px-3 py-2 text-xs font-bold"><CalendarDays className="h-4 w-4" />{data.billing.plan}</span><button onClick={() => void load()} className="rounded-xl border border-stone-200 bg-white p-2.5" aria-label="Refresh institute"><RefreshCw className="h-4 w-4" /></button></div></div><nav className="mt-6 flex gap-2 overflow-x-auto pb-1">{Object.entries(installedInstituteTabs).map(([key, label]) => <Link key={key} to={`/super-admin/institutes/${id}/${key}`} className={`whitespace-nowrap rounded-full px-4 py-2.5 text-sm font-bold ${activeTab === key ? 'bg-stone-950 text-white' : 'bg-stone-100 text-stone-600'}`}>{label}</Link>)}</nav></section><section>{content}</section></div>;
}
