import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, ArrowRight, CheckCircle2, Loader2 } from 'lucide-react';
import { superAdminInstituteApi } from './api';
import type { OnboardingInput } from './types';

const initial: OnboardingInput = { owner: { name: '', phone: '', email: '' }, institute: { name: '', city: '', area: '', address: '' }, access: { kind: 'FULL' }, billing: { plan: 'BASIC', trialDays: 14, discountPercent: 0 }, limits: { maxStudents: 100, quizCredits: 0 }, marketplace: { isPubliclyListed: true, isVerified: false } };
const steps = ['Owner', 'Institute', 'Access', 'Billing', 'Limits', 'Review'];

export function OnboardingWizard() {
  const [value, setValue] = useState(initial);
  const [step, setStep] = useState(0);
  const [preview, setPreview] = useState<unknown>(null);
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const [idempotencyKey] = useState(() => crypto.randomUUID());
  const navigate = useNavigate();
  const valid = useMemo(() => step === 0 ? value.owner.name.trim().length > 1 && /\d{10,}/.test(value.owner.phone.replace(/\D/g, '')) : step === 1 ? value.institute.name.trim().length > 1 : true, [step, value]);
  const next = async () => {
    setError('');
    if (!valid) { setError('Complete the required fields before continuing.'); return; }
    if (step < 5) { setStep(current => current + 1); return; }
    setBusy(true);
    try {
      if (!preview) { setPreview((await superAdminInstituteApi.previewOnboarding(value)).summary); return; }
      const result = await superAdminInstituteApi.commitOnboarding(value, idempotencyKey);
      navigate(`/super-admin/institutes/${result.instituteId}`);
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to onboard institute'); }
    finally { setBusy(false); }
  };
  const input = 'w-full rounded-2xl border border-stone-200 bg-white px-4 py-3 text-sm outline-none focus:border-amber-500 focus:ring-4 focus:ring-amber-100';
  return <div className="mx-auto max-w-4xl"><button onClick={() => navigate('/super-admin/institutes')} className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-stone-600"><ArrowLeft className="h-4 w-4" />Back to institutes</button><section className="overflow-hidden rounded-[32px] border border-stone-200 bg-[#fffdf9] shadow-sm"><div className="border-b border-stone-200 p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[0.2em] text-amber-700">Guided onboarding</p><h2 className="mt-2 text-3xl font-black">Set up the institute correctly the first time.</h2><div className="mt-6 grid grid-cols-6 gap-2">{steps.map((label, index) => <button key={label} onClick={() => index <= step && setStep(index)} className={`rounded-xl px-2 py-2 text-[10px] font-black sm:text-xs ${index === step ? 'bg-stone-950 text-white' : index < step ? 'bg-amber-100 text-amber-900' : 'bg-stone-100 text-stone-400'}`}>{index + 1}. {label}</button>)}</div></div><div className="min-h-[330px] p-6 sm:p-8">
    {step === 0 ? <div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">Owner name</span><input className={input} value={value.owner.name} onChange={event => setValue(current => ({ ...current, owner: { ...current.owner, name: event.target.value } }))} /></label><label><span className="mb-2 block text-sm font-bold">Phone (login)</span><input className={input} value={value.owner.phone} onChange={event => setValue(current => ({ ...current, owner: { ...current.owner, phone: event.target.value } }))} /></label><label><span className="mb-2 block text-sm font-bold">Email</span><input className={input} type="email" value={value.owner.email} onChange={event => setValue(current => ({ ...current, owner: { ...current.owner, email: event.target.value } }))} /></label></div> : null}
    {step === 1 ? <div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">Institute name</span><input className={input} value={value.institute.name} onChange={event => setValue(current => ({ ...current, institute: { ...current.institute, name: event.target.value } }))} /></label>{(['city', 'area', 'address'] as const).map(field => <label key={field} className={field === 'address' ? 'sm:col-span-2' : ''}><span className="mb-2 block text-sm font-bold capitalize">{field}</span><input className={input} value={value.institute[field]} onChange={event => setValue(current => ({ ...current, institute: { ...current.institute, [field]: event.target.value } }))} /></label>)}</div> : null}
    {step === 2 ? <div className="grid gap-3 sm:grid-cols-3">{(['FULL', 'PAGE_ONLY', 'QUIZ_ONLY'] as const).map(kind => <button key={kind} onClick={() => setValue(current => ({ ...current, access: { kind } }))} className={`rounded-2xl border p-5 text-left ${value.access.kind === kind ? 'border-stone-950 bg-stone-950 text-white' : 'border-stone-200 bg-white'}`}><p className="font-black">{kind.replace('_', ' ')}</p><p className="mt-2 text-xs opacity-70">{kind === 'FULL' ? 'Complete coaching management.' : kind === 'PAGE_ONLY' ? 'Marketplace and leads only.' : 'Quiz credits without ERP access.'}</p></button>)}</div> : null}
    {step === 3 ? <div className="grid gap-4 sm:grid-cols-3"><label><span className="mb-2 block text-sm font-bold">Plan</span><select className={input} value={value.billing.plan} onChange={event => setValue(current => ({ ...current, billing: { ...current.billing, plan: event.target.value as OnboardingInput['billing']['plan'] } }))}><option>FREE</option><option>BASIC</option><option>PRO</option><option>ENTERPRISE</option></select></label><label><span className="mb-2 block text-sm font-bold">Trial days</span><input className={input} type="number" value={value.billing.trialDays} onChange={event => setValue(current => ({ ...current, billing: { ...current.billing, trialDays: Number(event.target.value) } }))} /></label><label><span className="mb-2 block text-sm font-bold">Discount %</span><input className={input} type="number" value={value.billing.discountPercent} onChange={event => setValue(current => ({ ...current, billing: { ...current.billing, discountPercent: Number(event.target.value) } }))} /></label></div> : null}
    {step === 4 ? <div className="grid gap-4 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-bold">Student capacity</span><input className={input} type="number" value={value.limits.maxStudents} onChange={event => setValue(current => ({ ...current, limits: { ...current.limits, maxStudents: Number(event.target.value) } }))} /></label><label><span className="mb-2 block text-sm font-bold">Quiz credits</span><input className={input} type="number" value={value.limits.quizCredits} onChange={event => setValue(current => ({ ...current, limits: { ...current.limits, quizCredits: Number(event.target.value) } }))} /></label><label className="flex items-center gap-3 rounded-2xl border border-stone-200 bg-white p-4"><input type="checkbox" checked={value.marketplace.isPubliclyListed} onChange={event => setValue(current => ({ ...current, marketplace: { ...current.marketplace, isPubliclyListed: event.target.checked } }))} /><span className="font-bold">Publish Marketplace listing</span></label><label className="flex items-center gap-3 rounded-2xl border border-stone-200 bg-white p-4"><input type="checkbox" checked={value.marketplace.isVerified} onChange={event => setValue(current => ({ ...current, marketplace: { ...current.marketplace, isVerified: event.target.checked } }))} /><span className="font-bold">Mark as manually verified</span></label></div> : null}
    {step === 5 ? <div>{preview ? <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><div className="flex items-center gap-2 font-black text-emerald-800"><CheckCircle2 className="h-5 w-5" />Server validation passed</div><pre className="mt-4 max-h-52 overflow-auto whitespace-pre-wrap text-xs text-emerald-900">{JSON.stringify(preview, null, 2)}</pre></div> : <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-stone-100 p-4"><p className="text-xs font-black uppercase text-stone-400">Owner</p><p className="mt-2 font-black">{value.owner.name}</p><p className="text-sm text-stone-600">{value.owner.phone}</p></div><div className="rounded-2xl bg-stone-100 p-4"><p className="text-xs font-black uppercase text-stone-400">Institute</p><p className="mt-2 font-black">{value.institute.name}</p><p className="text-sm text-stone-600">{value.institute.city || 'City not set'}</p></div><div className="rounded-2xl bg-stone-100 p-4"><p className="text-xs font-black uppercase text-stone-400">Access</p><p className="mt-2 font-black">{value.access.kind}</p></div><div className="rounded-2xl bg-stone-100 p-4"><p className="text-xs font-black uppercase text-stone-400">Plan</p><p className="mt-2 font-black">{value.billing.plan} · {value.billing.trialDays} trial days</p></div></div>}</div> : null}
    {error ? <p className="mt-5 rounded-xl bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">{error}</p> : null}
  </div><div className="flex items-center justify-between border-t border-stone-200 p-5 sm:px-8"><button disabled={step === 0} onClick={() => { setPreview(null); setStep(current => current - 1); }} className="inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold disabled:opacity-30"><ArrowLeft className="h-4 w-4" />Back</button><button onClick={() => void next()} disabled={busy} className="inline-flex items-center gap-2 rounded-2xl bg-stone-950 px-5 py-3 text-sm font-black text-white disabled:opacity-50">{busy ? <Loader2 className="h-4 w-4 animate-spin" /> : null}{step < 5 ? 'Continue' : preview ? 'Create institute' : 'Validate with server'}<ArrowRight className="h-4 w-4" /></button></div></section></div>;
}
