import { useState } from 'react';
import { superAdminInstituteApi } from './api';
import type { InstituteWorkspaceData } from './types';

export function StructuredConfigForm({ instituteId, data, expectedUpdatedAt, onSaved }: { instituteId: string; data: InstituteWorkspaceData['usage']; expectedUpdatedAt: string; onSaved: () => void }) {
  const [form, setForm] = useState({ maxStudents: data.maxStudents, quizCredits: data.quizCredits, isQuizOnly: data.isQuizOnly, allowedClasses: data.allowedClasses.join(', '), subjects: data.subjects.join(', '), requiresGrades: data.requiresGrades, reason: '' });
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setMessage(''); try { await superAdminInstituteApi.updateConfiguration(instituteId, { expectedUpdatedAt, reason: form.reason, maxStudents: form.maxStudents, quizCredits: form.quizCredits, isQuizOnly: form.isQuizOnly, allowedClasses: form.allowedClasses.split(',').map(value => value.trim()).filter(Boolean), subjects: form.subjects.split(',').map(value => value.trim()).filter(Boolean), requiresGrades: form.requiresGrades }); setMessage('Configuration saved.'); onSaved(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : 'Save failed'); } finally { setSaving(false); } };
  const input = 'w-full rounded-xl border border-stone-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-amber-500';
  return <form onSubmit={save} className="grid gap-4 rounded-[24px] border border-stone-200 bg-white p-5 sm:grid-cols-2"><label><span className="mb-2 block text-sm font-bold">Student capacity</span><input className={input} type="number" value={form.maxStudents} onChange={event => setForm(current => ({ ...current, maxStudents: Number(event.target.value) }))} /></label><label><span className="mb-2 block text-sm font-bold">Quiz credits</span><input className={input} type="number" value={form.quizCredits} onChange={event => setForm(current => ({ ...current, quizCredits: Number(event.target.value) }))} /></label><label><span className="mb-2 block text-sm font-bold">Classes</span><input className={input} value={form.allowedClasses} onChange={event => setForm(current => ({ ...current, allowedClasses: event.target.value }))} /></label><label><span className="mb-2 block text-sm font-bold">Subjects</span><input className={input} value={form.subjects} onChange={event => setForm(current => ({ ...current, subjects: event.target.value }))} /></label><label className="flex items-center gap-3"><input type="checkbox" checked={form.isQuizOnly} onChange={event => setForm(current => ({ ...current, isQuizOnly: event.target.checked }))} /><span className="font-bold">Quiz-only access</span></label><label className="flex items-center gap-3"><input type="checkbox" checked={form.requiresGrades} onChange={event => setForm(current => ({ ...current, requiresGrades: event.target.checked }))} /><span className="font-bold">Require grades</span></label><label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">Reason for change</span><input className={input} value={form.reason} onChange={event => setForm(current => ({ ...current, reason: event.target.value }))} placeholder="Required for the audit trail" /></label><div className="flex items-center justify-between sm:col-span-2"><p className="text-sm font-semibold text-stone-500">{message}</p><button disabled={saving || form.reason.trim().length < 10} className="rounded-xl bg-stone-950 px-4 py-2.5 text-sm font-black text-white disabled:opacity-40">{saving ? 'Saving…' : 'Save configuration'}</button></div></form>;
}
