import { useState } from 'react';
import { superAdminInstituteApi } from './api';
import type { InstituteWorkspaceData } from './types';

export function StructuredConfigForm({ instituteId, data, expectedUpdatedAt, onSaved }: { instituteId: string; data: InstituteWorkspaceData['usage']; expectedUpdatedAt: string; onSaved: () => void }) {
  const [form, setForm] = useState({ allowedClasses: data.allowedClasses.join(', '), subjects: data.subjects.join(', '), requiresGrades: data.requiresGrades, reason: '' });
  const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setMessage(''); try { await superAdminInstituteApi.updateConfiguration(instituteId, { expectedUpdatedAt, reason: form.reason, allowedClasses: form.allowedClasses.split(',').map(v => v.trim()).filter(Boolean), subjects: form.subjects.split(',').map(v => v.trim()).filter(Boolean), requiresGrades: form.requiresGrades }); setMessage('Configuration saved.'); onSaved(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : 'Save failed'); } finally { setSaving(false); } };
  const input = 'w-full rounded-xl border border-stone-200 bg-white px-3 py-2.5 text-sm outline-none focus:border-amber-500';
  return <form onSubmit={save} className="grid gap-4 rounded-[24px] border border-stone-200 bg-white p-5 sm:grid-cols-2"><div className="sm:col-span-2 rounded-xl bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800">All plans support unlimited students. Quiz balances are managed through Billing operations.</div><label><span className="mb-2 block text-sm font-bold">Classes</span><input className={input} value={form.allowedClasses} onChange={e => setForm(c => ({ ...c, allowedClasses: e.target.value }))} /></label><label><span className="mb-2 block text-sm font-bold">Subjects</span><input className={input} value={form.subjects} onChange={e => setForm(c => ({ ...c, subjects: e.target.value }))} /></label><label className="flex items-center gap-3"><input type="checkbox" checked={form.requiresGrades} onChange={e => setForm(c => ({ ...c, requiresGrades: e.target.checked }))} /><span className="font-bold">Require grades</span></label><label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">Reason for change</span><input className={input} value={form.reason} onChange={e => setForm(c => ({ ...c, reason: e.target.value }))} placeholder="Required for the audit trail" /></label><div className="flex items-center justify-between sm:col-span-2"><p className="text-sm font-semibold text-stone-500">{message}</p><button disabled={saving || form.reason.trim().length < 10} className="rounded-xl bg-stone-950 px-4 py-2.5 text-sm font-black text-white disabled:opacity-40">{saving ? 'Saving…' : 'Save configuration'}</button></div></form>;
}
