import { useEffect, useState } from 'react';
import { Building2, CheckCircle2, ExternalLink, Loader2, LockKeyhole, MessageSquareText, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import toast from 'react-hot-toast';
import { useSuperAdminReauth } from '../superadmin-shell/ReauthDialog';
import { superAdminSupportApi } from './api';
import type { SupportStatus, SupportTicket } from './types';
import { setSupportSession } from '../superadmin-shell/supportSession';

const transitions: Record<SupportStatus, SupportStatus[]> = { NEW: ['IN_PROGRESS', 'WAITING_ON_INSTITUTE', 'RESOLVED'], IN_PROGRESS: ['WAITING_ON_INSTITUTE', 'RESOLVED'], WAITING_ON_INSTITUTE: ['IN_PROGRESS', 'RESOLVED'], RESOLVED: ['IN_PROGRESS', 'CLOSED'], CLOSED: [] };

export function TicketWorkspace({ ticketId, onUpdated }: { ticketId?: string; onUpdated: () => void }) {
  const [ticket, setTicket] = useState<SupportTicket | null>(null);
  const [body, setBody] = useState('');
  const [visibility, setVisibility] = useState<'PUBLIC' | 'INTERNAL'>('PUBLIC');
  const [resolution, setResolution] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const reauth = useSuperAdminReauth();
  const load = async () => { if (!ticketId) return; setError(''); try { setTicket(await superAdminSupportApi.ticket(ticketId)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load ticket'); } };
  useEffect(() => { setTicket(null); void load(); }, [ticketId]);
  if (!ticketId) return <section className="grid min-h-[560px] place-items-center rounded-[26px] border border-dashed border-stone-300 bg-white/50 p-8 text-center"><div><MessageSquareText className="mx-auto h-9 w-9 text-stone-300" /><h2 className="mt-4 text-xl font-black">Select a support ticket</h2><p className="mt-2 text-sm text-stone-500">Open a ticket to reply, add internal context, change status, or start an audited support session.</p></div></section>;
  if (!ticket) return <section className="grid min-h-[560px] place-items-center rounded-[26px] border border-stone-200 bg-white"><div className="text-center">{error ? <p className="text-sm font-semibold text-rose-700">{error}</p> : <Loader2 className="mx-auto h-6 w-6 animate-spin text-stone-400" />}</div></section>;
  const send = async () => { if (body.trim().length < 2) return; setBusy(true); setError(''); try { const updated = await superAdminSupportApi.reply(ticket.id, { visibility, body, expectedUpdatedAt: ticket.updatedAt }); setBody(''); setTicket(updated); await load(); onUpdated(); toast.success(visibility === 'PUBLIC' ? 'Reply sent' : 'Internal note added'); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to send message'); } finally { setBusy(false); } };
  const transition = async (status: SupportStatus) => { setBusy(true); setError(''); try { const updated = await superAdminSupportApi.transition(ticket.id, { status, expectedUpdatedAt: ticket.updatedAt, ...(status === 'RESOLVED' ? { resolutionSummary: resolution } : {}) }); setTicket(updated); await load(); onUpdated(); toast.success(`Ticket moved to ${status.replace(/_/g, ' ').toLowerCase()}`); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update ticket'); } finally { setBusy(false); } };
  const startSession = async () => { setBusy(true); setError(''); try { const reason = `Resolve ${ticket.reference}: ${ticket.subject}`; const challengeId = await reauth.request('SUPPORT_SESSION'); const result = await superAdminSupportApi.startSession({ instituteId: ticket.instituteId, ticketId: ticket.id, reason }, challengeId); setSupportSession({ sessionId: result.session.id, token: result.supportToken, instituteId: ticket.instituteId, instituteName: ticket.institute.name, reason, expiresAt: result.session.expiresAt, ticketId: ticket.id, ticketReference: ticket.reference }); toast.success(`Audited session active until ${new Date(result.session.expiresAt).toLocaleTimeString()}`); window.location.assign('/dashboard'); } catch (reasonValue) { setError(reasonValue instanceof Error ? reasonValue.message : 'Unable to start support session'); } finally { setBusy(false); } };
  return <section className="overflow-hidden rounded-[26px] border border-stone-200 bg-[#fffdf9] shadow-sm">
    <header className="border-b border-stone-200 p-5 sm:p-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-start xl:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-black uppercase tracking-wider text-amber-700">{ticket.reference}</span><span className="rounded-full bg-stone-100 px-2.5 py-1 text-[10px] font-black">{ticket.status.replace(/_/g, ' ')}</span><span className="rounded-full bg-rose-50 px-2.5 py-1 text-[10px] font-black text-rose-700">{ticket.priority}</span></div><h2 className="mt-2 text-2xl font-black">{ticket.subject}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-stone-600">{ticket.description}</p></div><button onClick={() => void startSession()} disabled={busy} className="inline-flex shrink-0 items-center justify-center gap-2 rounded-xl bg-stone-950 px-4 py-3 text-sm font-black text-white disabled:opacity-50"><ShieldCheck className="h-4 w-4" />Start audited support session</button></div>
      <div className="mt-5 flex flex-wrap gap-3 rounded-2xl bg-stone-100/70 p-4 text-sm"><Building2 className="h-5 w-5 text-stone-400" /><div className="flex-1"><Link to={`/super-admin/institutes/${ticket.instituteId}`} className="font-black hover:underline">{ticket.institute.name}</Link><p className="mt-1 text-xs text-stone-500">{ticket.institute.teacherName || 'Owner not set'} · {ticket.institute.phoneNumber || ticket.institute.email || 'No contact'}</p></div><Link to={`/super-admin/institutes/${ticket.instituteId}/support`} className="inline-flex items-center gap-1 text-xs font-black text-amber-800">Institute 360 <ExternalLink className="h-3 w-3" /></Link></div>
    </header>
    <div className="grid xl:grid-cols-[minmax(0,1fr)_280px]"><div className="space-y-4 p-5 sm:p-6"><h3 className="text-xs font-black uppercase tracking-wider text-stone-400">Conversation</h3>{ticket.messages?.map(message => <article key={message.id} className={`max-w-3xl rounded-2xl border p-4 ${message.visibility === 'INTERNAL' ? 'border-amber-200 bg-amber-50' : 'border-stone-200 bg-white'}`}><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-wider text-stone-400">{message.visibility === 'INTERNAL' ? <LockKeyhole className="h-3 w-3 text-amber-700" /> : <MessageSquareText className="h-3 w-3" />}{message.visibility} · {message.authorAdmin?.username || 'Institute'} · {new Date(message.createdAt).toLocaleString()}</div><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-stone-700">{message.body}</p></article>)}{!ticket.messages?.length ? <p className="rounded-2xl border border-dashed border-stone-300 p-5 text-sm text-stone-500">No replies yet.</p> : null}
      <div className={`rounded-2xl border p-4 ${visibility === 'INTERNAL' ? 'border-amber-200 bg-amber-50' : 'border-stone-200 bg-white'}`}><div className="flex items-center justify-between gap-3"><p className="text-sm font-black">Add response</p><div className="flex rounded-xl bg-stone-100 p-1"><button onClick={() => setVisibility('PUBLIC')} className={`rounded-lg px-3 py-1.5 text-xs font-bold ${visibility === 'PUBLIC' ? 'bg-white shadow-sm' : ''}`}>Public reply</button><button onClick={() => setVisibility('INTERNAL')} className={`rounded-lg px-3 py-1.5 text-xs font-bold ${visibility === 'INTERNAL' ? 'bg-amber-200 text-amber-950' : ''}`}>Internal note</button></div></div><textarea value={body} onChange={event => setBody(event.target.value)} className="mt-3 min-h-28 w-full resize-y rounded-xl border border-stone-200 bg-white p-3 text-sm outline-none focus:border-amber-500" placeholder={visibility === 'PUBLIC' ? 'Write a response visible to the institute…' : 'Add internal operational context…'} /><div className="mt-3 flex items-center justify-between"><p className="text-xs text-stone-500">{visibility === 'INTERNAL' ? 'Never shown to institute users.' : 'Institute users will see this reply.'}</p><button onClick={() => void send()} disabled={busy || body.trim().length < 2} className="rounded-xl bg-stone-950 px-4 py-2.5 text-sm font-black text-white disabled:opacity-40">Send</button></div></div>{error ? <p className="rounded-xl bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-700">{error}</p> : null}</div>
      <aside className="border-t border-stone-200 bg-stone-50 p-5 xl:border-l xl:border-t-0"><p className="text-xs font-black uppercase tracking-wider text-stone-400">Workflow</p><div className="mt-4 space-y-2">{transitions[ticket.status].map(status => <div key={status}>{status === 'RESOLVED' ? <textarea value={resolution} onChange={event => setResolution(event.target.value)} placeholder="Public resolution summary…" className="mb-2 min-h-20 w-full rounded-xl border border-stone-200 bg-white p-3 text-xs outline-none" /> : null}<button onClick={() => void transition(status)} disabled={busy || (status === 'RESOLVED' && resolution.trim().length < 10)} className="flex w-full items-center gap-2 rounded-xl border border-stone-200 bg-white px-3 py-2.5 text-left text-xs font-black disabled:opacity-40"><CheckCircle2 className="h-4 w-4 text-emerald-600" />Move to {status.replace(/_/g, ' ')}</button></div>)}{transitions[ticket.status].length === 0 ? <p className="text-xs text-stone-500">This ticket is closed.</p> : null}</div></aside></div>
  </section>;
}
